"""change credit logic

Revision ID: 0ddc604d88b9
Revises: 6b60bc442354
Create Date: 2025-10-24 13:20:48.264882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddc604d88b9'
down_revision: Union[str, Sequence[str], None] = '6b60bc442354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers_buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('building_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_number'], ['buildings.building_number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certifications',
    sa.Column('credit', sa.Boolean(), nullable=False),
    sa.Column('differentiated_credit', sa.Boolean(), nullable=False),
    sa.Column('course_project', sa.Boolean(), nullable=False),
    sa.Column('course_work', sa.Boolean(), nullable=False),
    sa.Column('control_work', sa.Boolean(), nullable=False),
    sa.Column('other_form', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['subjects_in_cycle_hours.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'groups', ['group_name'])
    op.create_unique_constraint(None, 'specialties', ['speciality_code'])
    op.drop_column('subjects_in_cycle', 'course_work')
    op.drop_column('subjects_in_cycle', 'credit')
    op.drop_column('subjects_in_cycle', 'other_form')
    op.drop_column('subjects_in_cycle', 'control_work')
    op.drop_column('subjects_in_cycle', 'differentiated_credit')
    op.drop_column('subjects_in_cycle', 'course_project')
    op.create_unique_constraint(None, 'teacher_categories', ['teacher_category'])
    op.create_unique_constraint(None, 'teachers', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'teacher_categories', type_='unique')
    op.add_column('subjects_in_cycle', sa.Column('course_project', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subjects_in_cycle', sa.Column('differentiated_credit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subjects_in_cycle', sa.Column('control_work', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subjects_in_cycle', sa.Column('other_form', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subjects_in_cycle', sa.Column('credit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subjects_in_cycle', sa.Column('course_work', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'specialties', type_='unique')
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_table('certifications')
    op.drop_table('teachers_buildings')
    # ### end Alembic commands ###
