"""Add unique on teacher.email and teacher.phone_number

Revision ID: 19003789b626
Revises: 44877c9ddb66
Create Date: 2025-08-14 08:43:38.738558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19003789b626'
down_revision: Union[str, Sequence[str], None] = '44877c9ddb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'teachers', ['email'])
    op.create_unique_constraint(None, 'teachers', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'teachers', type_='unique')
    # ### end Alembic commands ###
