"""Remove salary_rate column from Teacher table

Revision ID: 1d6eaa7bb3e6
Revises: 0ddc604d88b9
Create Date: 2025-11-20 16:06:00.475535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6eaa7bb3e6'
down_revision: Union[str, Sequence[str], None] = '0ddc604d88b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'salary_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('salary_rate', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
