"""Add ondelete and onupdate for foreign key in group

Revision ID: 310d2ac505ed
Revises: 19003789b626
Create Date: 2025-08-14 08:46:31.971502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310d2ac505ed'
down_revision: Union[str, Sequence[str], None] = '19003789b626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('groups_group_advisor_id_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'teachers', ['group_advisor_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_group_advisor_id_fkey'), 'groups', 'teachers', ['group_advisor_id'], ['id'])
    # ### end Alembic commands ###
