"""Add onupdate and ondelete operation for some models

Revision ID: 44877c9ddb66
Revises: 3247042728c1
Create Date: 2025-08-09 14:01:12.477256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44877c9ddb66'
down_revision: Union[str, Sequence[str], None] = '3247042728c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cabinets_building_number_fkey'), 'cabinets', type_='foreignkey')
    op.create_foreign_key(None, 'cabinets', 'buildings', ['building_number'], ['building_number'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(op.f('employment_teachers_teacher_id_fkey'), 'employment_teachers', type_='foreignkey')
    op.create_foreign_key(None, 'employment_teachers', 'teachers', ['teacher_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('sessions_group_name_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_subject_code_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_cabinet_number_building_number_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_teacher_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'cabinets', ['cabinet_number', 'building_number'], ['cabinet_number', 'building_number'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sessions', 'subjects', ['subject_code'], ['subject_code'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sessions', 'teachers', ['teacher_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sessions', 'groups', ['group_name'], ['group_name'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('teacher_requests_teacher_id_fkey'), 'teacher_requests', type_='foreignkey')
    op.drop_constraint(op.f('teacher_requests_subject_code_fkey'), 'teacher_requests', type_='foreignkey')
    op.drop_constraint(op.f('teacher_requests_group_name_fkey'), 'teacher_requests', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_requests', 'groups', ['group_name'], ['group_name'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'teacher_requests', 'subjects', ['subject_code'], ['subject_code'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'teacher_requests', 'teachers', ['teacher_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_requests', type_='foreignkey')
    op.drop_constraint(None, 'teacher_requests', type_='foreignkey')
    op.drop_constraint(None, 'teacher_requests', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_requests_group_name_fkey'), 'teacher_requests', 'groups', ['group_name'], ['group_name'])
    op.create_foreign_key(op.f('teacher_requests_subject_code_fkey'), 'teacher_requests', 'subjects', ['subject_code'], ['subject_code'])
    op.create_foreign_key(op.f('teacher_requests_teacher_id_fkey'), 'teacher_requests', 'teachers', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_teacher_id_fkey'), 'sessions', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('sessions_cabinet_number_building_number_fkey'), 'sessions', 'cabinets', ['cabinet_number', 'building_number'], ['cabinet_number', 'building_number'])
    op.create_foreign_key(op.f('sessions_subject_code_fkey'), 'sessions', 'subjects', ['subject_code'], ['subject_code'])
    op.create_foreign_key(op.f('sessions_group_name_fkey'), 'sessions', 'groups', ['group_name'], ['group_name'])
    op.drop_constraint(None, 'employment_teachers', type_='foreignkey')
    op.create_foreign_key(op.f('employment_teachers_teacher_id_fkey'), 'employment_teachers', 'teachers', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'cabinets', type_='foreignkey')
    op.create_foreign_key(op.f('cabinets_building_number_fkey'), 'cabinets', 'buildings', ['building_number'], ['building_number'])
    # ### end Alembic commands ###
