"""debug twice one-to-many relation for session

Revision ID: 494c2680950e
Revises: 538492c0829d
Create Date: 2025-07-22 15:53:57.916858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494c2680950e'
down_revision: Union[str, Sequence[str], None] = '538492c0829d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'groups', ['group_name'])
    op.create_unique_constraint(None, 'specialties', ['speciality_code'])
    op.create_unique_constraint(None, 'subjects', ['subject_code'])
    op.create_unique_constraint(None, 'teachers', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_constraint(None, 'specialties', type_='unique')
    op.drop_constraint(None, 'groups', type_='unique')
    # ### end Alembic commands ###
