"""Create database version 2.0

Revision ID: 538492c0829d
Revises: 
Create Date: 2025-07-18 11:18:25.391184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538492c0829d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('building_number', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('building_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('building_number')
    )
    op.create_table('specialties',
    sa.Column('speciality_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('speciality_code'),
    sa.UniqueConstraint('speciality_code')
    )
    op.create_table('subjects',
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('subject_code'),
    sa.UniqueConstraint('subject_code')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('fathername', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cabinets',
    sa.Column('cabinet_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('cabinet_state', sa.String(), nullable=True),
    sa.Column('building_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_number'], ['buildings.building_number'], ),
    sa.PrimaryKeyConstraint('cabinet_number', 'building_number')
    )
    op.create_table('employment_teachers',
    sa.Column('date_start_period', sa.Date(), nullable=False),
    sa.Column('date_end_period', sa.Date(), nullable=False),
    sa.Column('monday', sa.String(), nullable=True),
    sa.Column('tuesday', sa.String(), nullable=True),
    sa.Column('wednesday', sa.String(), nullable=True),
    sa.Column('thursday', sa.String(), nullable=True),
    sa.Column('friday', sa.String(), nullable=True),
    sa.Column('saturday', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('date_start_period', 'date_end_period', 'teacher_id')
    )
    op.create_table('groups',
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('quantity_students', sa.Integer(), nullable=True),
    sa.Column('group_advisor_id', sa.Integer(), nullable=True),
    sa.Column('speciality_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_advisor_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['speciality_code'], ['specialties.speciality_code'], ),
    sa.PrimaryKeyConstraint('group_name'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('teacher_subject',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.subject_code'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], )
    )
    op.create_table('curriculums',
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.Column('lectures_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('laboratory_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('practical_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_name'], ['groups.group_name'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.subject_code'], ),
    sa.PrimaryKeyConstraint('semester_number', 'group_name', 'subject_code')
    )
    op.create_table('sessions',
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('cabinet_number', sa.Integer(), nullable=False),
    sa.Column('building_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_number', 'building_number'], ['cabinets.cabinet_number', 'cabinets.building_number'], ),
    sa.ForeignKeyConstraint(['group_name'], ['groups.group_name'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.subject_code'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('session_number', 'date', 'group_name')
    )
    op.create_table('teacher_requests',
    sa.Column('date_request', sa.Date(), nullable=False),
    sa.Column('lectures_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('laboratory_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('practice_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_name'], ['groups.group_name'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.subject_code'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('date_request', 'teacher_id', 'subject_code', 'group_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_requests')
    op.drop_table('sessions')
    op.drop_table('curriculums')
    op.drop_table('teacher_subject')
    op.drop_table('groups')
    op.drop_table('employment_teachers')
    op.drop_table('cabinets')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('specialties')
    op.drop_table('buildings')
    # ### end Alembic commands ###
