"""new start

Revision ID: 6b60bc442354
Revises: 
Create Date: 2025-10-22 14:45:40.048180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b60bc442354'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('building_number', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('building_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('building_number')
    )
    op.create_table('session_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('specialties',
    sa.Column('speciality_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('speciality_code'),
    sa.UniqueConstraint('speciality_code')
    )
    op.create_table('teacher_categories',
    sa.Column('teacher_category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('teacher_category'),
    sa.UniqueConstraint('teacher_category')
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('cabinets',
    sa.Column('cabinet_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('cabinet_state', sa.String(), nullable=True),
    sa.Column('building_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_number'], ['buildings.building_number'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cabinet_number', 'building_number')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('speciality_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['speciality_code'], ['specialties.speciality_code'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('fathername', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('salary_rate', sa.Numeric(), nullable=True),
    sa.Column('teacher_category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_category'], ['teacher_categories.teacher_category'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('chapter_in_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('quantity_students', sa.Integer(), nullable=True),
    sa.Column('group_advisor_id', sa.Integer(), nullable=True),
    sa.Column('speciality_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_advisor_id'], ['teachers.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['speciality_code'], ['specialties.speciality_code'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('group_name'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('semesters',
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('weeks', sa.Double(), nullable=False),
    sa.Column('practice_weeks', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('semester', 'plan_id')
    )
    op.create_table('cycle_in_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contains_modules', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chapter_in_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_in_plan_id'], ['chapter_in_plan.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_in_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('cycle_in_chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_in_chapter_id'], ['cycle_in_chapter.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects_in_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('credit', sa.String(), nullable=False),
    sa.Column('differentiated_credit', sa.String(), nullable=False),
    sa.Column('course_project', sa.String(), nullable=False),
    sa.Column('course_work', sa.String(), nullable=False),
    sa.Column('control_work', sa.String(), nullable=False),
    sa.Column('other_form', sa.String(), nullable=False),
    sa.Column('module_in_cycle_id', sa.Integer(), nullable=True),
    sa.Column('cycle_in_chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_in_chapter_id'], ['cycle_in_chapter.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_in_cycle_id'], ['module_in_cycle.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streams',
    sa.Column('stream_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_name'], ['groups.group_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects_in_cycle.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stream_id', 'group_name', 'subject_id')
    )
    op.create_table('subjects_in_cycle_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('self_study_hours', sa.Integer(), nullable=False),
    sa.Column('lectures_hours', sa.Integer(), nullable=False),
    sa.Column('laboratory_hours', sa.Integer(), nullable=False),
    sa.Column('practical_hours', sa.Integer(), nullable=False),
    sa.Column('course_project_hours', sa.Integer(), nullable=False),
    sa.Column('consultation_hours', sa.Integer(), nullable=False),
    sa.Column('intermediate_assessment_hours', sa.Integer(), nullable=False),
    sa.Column('subject_in_cycle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_in_cycle_id'], ['subjects_in_cycle.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers_in_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_in_cycle_hours_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_name'], ['groups.group_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_type'], ['session_types.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_in_cycle_hours_id'], ['subjects_in_cycle_hours.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('teacher_in_plan', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('cabinet_number', sa.Integer(), nullable=True),
    sa.Column('building_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_number', 'building_number'], ['cabinets.cabinet_number', 'cabinets.building_number'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_type'], ['session_types.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_in_plan'], ['teachers_in_plans.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_number', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('teachers_in_plans')
    op.drop_table('subjects_in_cycle_hours')
    op.drop_table('streams')
    op.drop_table('subjects_in_cycle')
    op.drop_table('module_in_cycle')
    op.drop_table('cycle_in_chapter')
    op.drop_table('semesters')
    op.drop_table('groups')
    op.drop_table('chapter_in_plan')
    op.drop_table('teachers')
    op.drop_table('plans')
    op.drop_table('cabinets')
    op.drop_table('tokens')
    op.drop_table('teacher_categories')
    op.drop_table('specialties')
    op.drop_table('session_types')
    op.drop_table('buildings')
    # ### end Alembic commands ###
