"""Add DELETE and UPDATE to Curriculum.subject_code and Curriculum.group_name

Revision ID: 785bdb2e3b55
Revises: 99c9bef4af85
Create Date: 2025-08-04 07:50:59.588258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785bdb2e3b55'
down_revision: Union[str, Sequence[str], None] = '99c9bef4af85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('curriculums_subject_code_fkey'), 'curriculums', type_='foreignkey')
    op.drop_constraint(op.f('curriculums_group_name_fkey'), 'curriculums', type_='foreignkey')
    op.create_foreign_key(None, 'curriculums', 'groups', ['group_name'], ['group_name'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'curriculums', 'subjects', ['subject_code'], ['subject_code'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curriculums', type_='foreignkey')
    op.drop_constraint(None, 'curriculums', type_='foreignkey')
    op.create_foreign_key(op.f('curriculums_group_name_fkey'), 'curriculums', 'groups', ['group_name'], ['group_name'])
    op.create_foreign_key(op.f('curriculums_subject_code_fkey'), 'curriculums', 'subjects', ['subject_code'], ['subject_code'])
    # ### end Alembic commands ###
