"""create users table

Revision ID: 980e3e57d8d4
Revises: 3f270f4920ac
Create Date: 2026-03-05 02:33:13.826264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980e3e57d8d4'
down_revision: Union[str, Sequence[str], None] = '3f270f4920ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'groups', ['group_name'])
    op.create_unique_constraint(None, 'payment_forms', ['payment_name'])
    op.create_unique_constraint(None, 'specialties', ['speciality_code'])
    op.create_unique_constraint(None, 'teacher_categories', ['teacher_category'])
    op.create_unique_constraint(None, 'teachers', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'teacher_categories', type_='unique')
    op.drop_constraint(None, 'specialties', type_='unique')
    op.drop_constraint(None, 'payment_forms', type_='unique')
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
