"""Add DELETE SET NULL to groups.speciality_code

Revision ID: 99c9bef4af85
Revises: d8397ef989bf
Create Date: 2025-07-30 13:05:48.854780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c9bef4af85'
down_revision: Union[str, Sequence[str], None] = 'd8397ef989bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'speciality_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('groups_speciality_code_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'specialties', ['speciality_code'], ['speciality_code'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_speciality_code_fkey'), 'groups', 'specialties', ['speciality_code'], ['speciality_code'], onupdate='CASCADE')
    op.alter_column('groups', 'speciality_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
