"""Add teacher_subject and teachers_groups many-to-many tables

Revision ID: a8dddeadea27
Revises: 310d2ac505ed
Create Date: 2025-09-13 11:22:49.856948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8dddeadea27'
down_revision: Union[str, Sequence[str], None] = '310d2ac505ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('teachers_groups',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_name'], ['groups.group_name'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers_groups')
    op.drop_table('tokens')
    # ### end Alembic commands ###
