"""Add new table payment_forms and relationship in group with it

Revision ID: d38ce9d9f97d
Revises: 1d6eaa7bb3e6
Create Date: 2025-11-20 16:48:56.799040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38ce9d9f97d'
down_revision: Union[str, Sequence[str], None] = '1d6eaa7bb3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_forms',
    sa.Column('payment_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('payment_name'),
    sa.UniqueConstraint('payment_name')
    )
    op.add_column('groups', sa.Column('payment_form', sa.String(), nullable=True))
    op.create_foreign_key(None, 'groups', 'payment_forms', ['payment_form'], ['payment_name'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'payment_form')
    op.drop_table('payment_forms')
    # ### end Alembic commands ###
