"""Add ON UPDATE CASCADE to groups.speciality_code

Revision ID: d8397ef989bf
Revises: 494c2680950e
Create Date: 2025-07-30 12:52:02.671310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8397ef989bf'
down_revision: Union[str, Sequence[str], None] = '494c2680950e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('groups_speciality_code_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'specialties', ['speciality_code'], ['speciality_code'], onupdate='CASCADE')
    op.alter_column('teacher_requests', 'lectures_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('teacher_requests', 'laboratory_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('teacher_requests', 'practice_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher_requests', 'practice_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('teacher_requests', 'laboratory_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('teacher_requests', 'lectures_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_speciality_code_fkey'), 'groups', 'specialties', ['speciality_code'], ['speciality_code'])
    # ### end Alembic commands ###
